/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayChapterRouteImport } from './routes/play.$chapter'
import { Route as AdminChaptersRouteImport } from './routes/admin.chapters'

const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayChapterRoute = PlayChapterRouteImport.update({
  id: '/play/$chapter',
  path: '/play/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChaptersRoute = AdminChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chapters': typeof ChaptersRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/play/$chapter': typeof PlayChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chapters': typeof ChaptersRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/play/$chapter': typeof PlayChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chapters': typeof ChaptersRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/play/$chapter': typeof PlayChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/chapters' | '/admin/chapters' | '/play/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/chapters' | '/admin/chapters' | '/play/$chapter'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chapters'
    | '/admin/chapters'
    | '/play/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChaptersRoute: typeof ChaptersRoute
  PlayChapterRoute: typeof PlayChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$chapter': {
      id: '/play/$chapter'
      path: '/play/$chapter'
      fullPath: '/play/$chapter'
      preLoaderRoute: typeof PlayChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chapters': {
      id: '/admin/chapters'
      path: '/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AdminChaptersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChaptersRoute: typeof AdminChaptersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChaptersRoute: AdminChaptersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChaptersRoute: ChaptersRoute,
  PlayChapterRoute: PlayChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
